name: dsc_kiet_mobile_app
description: Mobile application for dsc kiet
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.0.1
  supercharged: ^2.0.0
  font_awesome_flutter: ^9.0.0
  flutter_svg: ^0.21.0+1
  url_launcher: ^6.0.3
  google_maps_flutter: ^2.0.1
  curved_navigation_bar: ^0.3.7
  flutter_riverpod: ^0.14.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Regular.ttf
